---2차시도
CREATE TABLE STUDENT (
	STUDENT_NO	VARCHAR2(20)	NOT NULL,
	STUDENT_NAME  varchar2(20)		NOT NULL,
	PHONE	 varchar2(30)		NULL
);

COMMENT ON COLUMN STUDENT.STUDENT_NO IS '학생코드';

COMMENT ON COLUMN STUDENT.STUDENT_NAME IS '학생이름';

COMMENT ON COLUMN STUDENT.PHONE IS '학생연락처';

CREATE TABLE PLANNER (
	PLAN_DATE	   DATE		NOT NULL,
    STUDENT_NO	VARCHAR2(20)		NOT NULL,
    STUDY_TIME	number	DEFAULT 0	NOT NULL,
    STUDY_PERFORMANCE	VARCHAR2(20)	NOT NULL,
    CLASS_CODE	VARCHAR2(20)	NOT NULL
);


COMMENT ON COLUMN PLANNER.PLAN_DATE IS '날짜';

COMMENT ON COLUMN PLANNER.STUDENT_NO IS '학생코드';

COMMENT ON COLUMN PLANNER.STUDY_TIME IS '공부시간';

COMMENT ON COLUMN PLANNER.STUDY_PERFORMANCE IS '평가';

COMMENT ON COLUMN PLANNER.CLASS_CODE IS '과목코드';

CREATE TABLE CLASS (
	CLASS_CODE	VARCHAR2(20)	NOT NULL,
	CLASS_NAME	varchar2(30)		NOT NULL
);

COMMENT ON COLUMN CLASS.CLASS_CODE IS '과목코드';

COMMENT ON COLUMN CLASS.CLASS_NAME IS '과목명';

ALTER TABLE STUDENT ADD CONSTRAINT PK_STUDENT PRIMARY KEY (
	STUDENT_NO
);

ALTER TABLE PLANNER ADD CONSTRAINT PK_PLANNER PRIMARY KEY (
	PLAN_DATE,
	STUDENT_NO
);

ALTER TABLE CLASS ADD CONSTRAINT PK_CLASS PRIMARY KEY (
	CLASS_CODE
);

ALTER TABLE PLANNER ADD CONSTRAINT FK_STUDENT_TO_PLANNER_1 FOREIGN KEY (
	STUDENT_NO
)
REFERENCES STUDENT (
	STUDENT_NO
);

ALTER TABLE PLANNER ADD CONSTRAINT FK_CLASS_TO_PLANNER_1 FOREIGN KEY (
	CLASS_CODE
)
REFERENCES CLASS (
	CLASS_CODE
);

-- 시퀀스 생성 
CREATE SEQUENCE SEQ_STUDENT_NO
       INCREMENT BY 1
       START WITH 1
       MINVALUE 1
       MAXVALUE 9999
       NOCYCLE
       NOCACHE
       NOORDER;

       
-- CLASS_NO 시퀀스 생성
CREATE SEQUENCE CLASS_CODE
       INCREMENT BY 1
       START WITH 1
       MINVALUE 1
       MAXVALUE 9999
       NOCYCLE
       NOCACHE
       NOORDER;